version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${BATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - /Volumes/SSD/volumes:/var/lib/mysql

